In [17]:
import pandas as pd
import numpy as np

import requests


1. Pandas version 3.0.6

In [18]:
pd.__version__

'3.0.6'

In [19]:
url = r"https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"
df = pd.read_csv(url)


2. There are 10,000 records

In [20]:
df.dtypes

model_year               int64
origin                     str
fuel_type                  str
drivetrain                 str
num_doors                int64
engine_displacement      int64
num_cylinders            int64
horsepower             float64
vehicle_weight           int64
acceleration           float64
fuel_efficiency_mpg    float64
dtype: object

In [21]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [22]:
df.size

110000

In [23]:
df.shape

(10000, 11)

Q3. Fuel types: there are 3 fuel types

In [24]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

4. Columns with empty values is 2

5. Max fuel efficency for cars from asia 41.2

In [25]:
df['origin'].unique()

<StringArray>
['Europe', 'Asia', 'USA']
Length: 3, dtype: str

In [26]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

Q6 Median horsepower median is 254 and most common is 252, after fillna the median is the same 

In [27]:
median = df['horsepower'].median()
median

np.float64(254.0)

In [28]:
mode = df['horsepower'].mode()
mode

0    252.0
Name: horsepower, dtype: float64

In [29]:
new_median = df['horsepower'].fillna(median).median()
new_median

np.float64(254.0)

In [30]:
new_median == median

np.True_

7. Vehicle weights 0.369

In [50]:
X = df[df['origin']=='Asia'][['vehicle_weight', 'model_year']][0:7].to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [57]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result



In [59]:
matrix_matrix_multiplication(X.T,X)

array([[1.3195050e+08, 6.0750580e+07],
       [6.0750580e+07, 2.8041424e+07]])

In [61]:
XTX = (X.T).dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [63]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [66]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [73]:
XTX_invXT = XTX_inv.dot(X.T)
XTX_invXT

array([[-2.50082897e-04, -1.65786806e-05, -2.86196661e-04,
         3.99964853e-04, -1.18162927e-03,  1.10298508e-03,
         2.25354894e-04],
       [ 6.12974614e-04,  1.06954785e-04,  6.91249245e-04,
        -7.95968736e-04,  2.63152339e-03, -2.31749941e-03,
        -4.16221392e-04]])

In [74]:
result = XTX_invXT.dot(y)
result

array([0.13644777, 0.2327492 ])

In [75]:
result.sum()

np.float64(0.36919696904925486)